### ISSUE TITLE
Problem when loading pickle file with Python 3.4

### ISSUE THREAD

**Issue by tuannhtn** [ChrisYang/facefrontalisation#1]
Hello Yang,
I got this error when runing the code with Python 3.4:

Traceback (most recent call last):
  File "facefrontal.py", line 143, in <module>
    fronter = frontalizer('ref3d.pkl')
  File "facefrontal.py", line 41, in **init**
    ref = pkl.load(f)
TypeError: 'str' does not support the buffer interface

Could you upload a new version of pickle file ref3d.pkl for Python 3.x. Thank you.

**Comment by ChrisYang** [comment]
This is due to the incompatibility between Python2 and Python3. 
Try 
ref = pkl.load(f,encoding='latin1')
I do not have python 3 thus i did not test. Could you please let me know if it works.

**Comment by tuannhtn** [comment]
Thanks Yang. It works. In fact, I have just found the same solution from http://stackoverflow.com/questions/11305790/pickle-incompatability-of-numpy-arrays-between-python-2-and-3
