### ISSUE TITLE
Sample test image

### ISSUE THREAD

**Issue by nitish11** [ChrisYang/facefrontalisation#2]
Hi,

Can you give the instructions to use this code on a sample test image ??
How to generate ref3d.pkl for a new image?

Thanks

**Comment by sschnug** [comment]
I played around with this lib some time ago.

I always thought, that ref3d.pkl is the reference 3d-shape which is the core of the algorithm (look into the paper). This would mean, that this reference model keeps the same for all images you want to process (no per-image generation).
An excerpt from the paper's abstract:

```
Instead, we explore the simpler approach of using a single, unmodified, 3D surface as an approximation to the shape of all input faces
```

I don't remember, what was needed to use this lib, but the content of the main method already looks like you could just swap the path to test it on your image.

**Comment by nitish11** [comment]
Thanks for the reply. I will explore the code.
